apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
      - name: student-app
        image: us-central1-docker.pkg.dev/shrija/student/student-app:latest
        ports:
        - containerPort: 8080
